name: Deploy on GitHub Pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        env:
          PWD: ${{ secrets.PWD }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: export GIT_USER_NAME=opixelum
      - run: export GIT_USER_EMAIL=48217573+opixelum@users.noreply.github.com
      - run: export GIT_PASS=$PWD
      - run: GIT_USER=opixelum npm run deploy --if-present
